### ISSUE TITLE
Expose column keywords in Variable attrs

### ISSUE THREAD

**Issue by sjperkins** [ratt-ru/dask-ms#253]
- xova needs to copy SPECTRAL_WINDOW.REF_FREQUENCY column keywords from source to destination subtable.
- dask-ms is already starting to expose various metadata in xarray Dataset attrs
- dask-ms should do this in a consistent way. For example
  - Anything that uses dask-ms uses internally should should probably use `__daskms_metadata__`
  - `__casa_metadata__` might be a valid key that we could store things under.
  - Should `__casa_metadata__` live within `__daskms_metadata__`? 

/cc @bennahugo @jskenyon @landmanbester

**Comment by bennahugo** [comment]
Things like this in the column discriptors for each keyword has to be exposed in one way or another
```python
CASA <18>: tb.open("1491291289.1ghz.1.1ghz.4hrs.ms::SPECTRAL_WINDOW")
Out[18]: True

CASA <19>: tb.getcolkeywords("REF_FREQUENCY")
Out[19]: 
{'MEASINFO': {'TabRefCodes': array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 64], dtype=uint32),
  'TabRefTypes': array(['REST', 'LSRK', 'LSRD', 'BARY', 'GEO', 'TOPO', 'GALACTO', 'LGROUP',
         'CMB', 'Undefined'], 
        dtype='|S10'),
  'VarRefCol': 'MEAS_FREQ_REF',
  'type': 'frequency'},
 'QuantumUnits': array(['Hz'], 
       dtype='|S3')}
```

This is especially important because units and frames really do matter in practice (TIME for instance is not necessarily UTC -- it can be UT1 for instance and if this is not correctly propagated leapseconds will be added incorrectly).  The same goes for reference frequency. The rest frame is extremely important when it comes to line sciences to specify accurate dopler correction information

**Comment by bennahugo** [comment]
At this point we have two options. I can write routines (just like fixvis) to extract and fix the keyword tables and the units in the main table, or we can more coherently expose this with dask-ms. Option 1 is a kludge and will need to be redone for every application while I can probably crunch out option 2 in a day or 2.

However option 1 is really important to support for other data formats such as s3 buckets, pyarrow and xarray for the same reasons I mentioned in the comment above

**Comment by sjperkins** [comment]
I think that Option 2 is the best way forward.

> However option 2 is really important to support for other data formats such as s3 buckets, pyarrow and xarray for the same reasons I mentioned in the comment above. To be honest I don't even know if these more general formats can support metadata such as frames and units with arbitrary types - this may even need to live in a separate file.

As long as the metadata is json serialisable, there should be no problem storing this data in arrow/zarr. I don't anticipate any issues here, although there may be exotic types that may cause issues. Can you think of any offhand? numpy arrays aren't strictly json serialisable, but it should be easy enough to add in a hook for them. In fact, there's already some logic for this here:

https://github.com/ratt-ru/dask-ms/blob/0beef44ce8c527c681255ed81f3561477aa8df55/daskms/dataset_schema.py#L35-L61

There's probably some logic in the PyData ecosystem for sensibly handling this. I'll look out for this when I'm working on this next, but let me know if you know of anything!

**Comment by bennahugo** [comment]
I think the issue is, if we look back at the C++ data layer the keywords
can be anything from a simple data type to an entire table with columns.
This is set by the DataRecord valueholder object, which is like a bumpy
object array. I'm not sure all of this is necessarily serializable - you
would need to support numpy object arrays potentially. How about we store
them as an empty casacore table set with just descriptors and keywords as a
first pass that is base64 encoded and injected into the the system as json?

**Comment by sjperkins** [comment]
> I think the issue is, if we look back at the C++ data layer the keywords can be anything from a simple data type to an entire table with columns. This is set by the DataRecord valueholder object, which is like a bumpy object array. I'm not sure all of this is necessarily serializable - you would need to support numpy object arrays potentially. How about we store them as an empty casacore table set with just descriptors and keywords as a first pass that is base64 encoded and injected into the the system as json?

This is true, but I think it'd be a highly unusual MS and I'd be willing to just fall over here.
